"""MeshAxis: a lightweight representation of a device mesh axis.

A MeshAxis wraps a ``_MeshLayout`` from ``torch.distributed._mesh_layout``
and provides equality/hashing, set-inclusion (subgroup) checks, and
human-readable names derived from ProcessGroup ``group_desc`` annotations.

Unlike a ProcessGroup, a MeshAxis is a pure data descriptor -- it records
*which* ranks participate and how they are strided, but it does not own a
communicator.  Multiple ProcessGroups can correspond to the same MeshAxis.
"""

from __future__ import annotations

import contextlib
import os
import weakref
from collections.abc import Generator
from dataclasses import dataclass
from typing import overload, TYPE_CHECKING

from sixlib.spmd_types import _dist
from torch.distributed._local_tensor._c10d import _indices_to_layout
from torch.distributed._mesh_layout import _MeshLayout

if TYPE_CHECKING:
    from torch.distributed import ProcessGroup


# Global side table: MeshAxis -> set of human-readable names.
# Populated when converting a ProcessGroup whose ``group_desc`` is set.
_mesh_axis_names: dict[MeshAxis, set[str]] = {}

# Weak cache from ProcessGroup to MeshAxis so we don't recompute the layout
# every time.  WeakKeyDictionary ensures we don't prevent PG garbage
# collection.
_pg_to_mesh_axis: weakref.WeakKeyDictionary[ProcessGroup, MeshAxis] = (
    weakref.WeakKeyDictionary()
)

# When True, repr includes all names and the layout in curly braces,
# e.g. "TP/SP{4:1}".  When False (default), repr shows only the first
# name, e.g. "TP".
_debug_repr: bool = os.environ.get("MESH_AXIS_DEBUG", "") == "1"


@dataclass(frozen=True, slots=True, repr=False)
class MeshAxis:
    """A device mesh axis, identified by a CuTe-style layout of rank indices.

    Two MeshAxis objects are equal (and hash identically) when they describe
    the same set of ranks with the same striding pattern -- regardless of
    which ProcessGroup they were derived from.

    Attributes:
        layout: The underlying ``_MeshLayout`` (shape, stride) that generates
            the rank pattern for this axis.
    """

    layout: _MeshLayout

    def __post_init__(self) -> None:
        # Always store the coalesced form so that equivalent layouts compare
        # equal (e.g., (2,2):(2,1) == (4):(1)).
        object.__setattr__(self, "layout", self.layout.coalesce())

    # -- Set inclusion (subgroup checks) -----------------------------------

    def __le__(self, other: MeshAxis) -> bool:
        """True if self is a subgroup of (or equal to) other.

        A MeshAxis A is a subgroup of B when every rank generated by A
        is also generated by B (both starting from offset 0).
        """
        if not isinstance(other, MeshAxis):
            return NotImplemented
        if self == other:
            return True
        self_ranks = set(self.layout.all_ranks_from_zero())
        other_ranks = set(other.layout.all_ranks_from_zero())
        return self_ranks <= other_ranks

    def __lt__(self, other: MeshAxis) -> bool:
        if not isinstance(other, MeshAxis):
            return NotImplemented
        return self != other and self <= other

    def __ge__(self, other: MeshAxis) -> bool:
        if not isinstance(other, MeshAxis):
            return NotImplemented
        return other <= self

    def __gt__(self, other: MeshAxis) -> bool:
        if not isinstance(other, MeshAxis):
            return NotImplemented
        return other < self

    # -- Orthogonality -----------------------------------------------------

    def isorthogonal(self, *others: MeshAxis) -> bool:
        """True if self and all others are mutually orthogonal mesh axes.

        Axes are orthogonal when their combined layout generates a number
        of unique ranks equal to the product of their sizes -- they tile
        different dimensions of the mesh without rank collisions.

        Example::

            tp = MeshAxis.of(4, 1)    # ranks {0,1,2,3}
            dp = MeshAxis.of(2, 4)    # ranks {0,4}
            tp.isorthogonal(dp)      # True  -- 4*2 = 8 unique ranks
            tp.isorthogonal(tp)      # False -- same ranks collide
        """
        axes = (self,) + others
        shapes: list[int] = []
        strides: list[int] = []
        expected = 1
        for ax in axes:
            for s, d in ax.layout.sizes_and_strides:
                shapes.append(s)
                strides.append(d)
            expected *= ax.size()
        combined = _MeshLayout(tuple(shapes), tuple(strides))
        return len(set(combined.all_ranks_from_zero())) == expected

    # -- Size --------------------------------------------------------------

    def size(self) -> int:
        """Number of ranks in this mesh axis (product of layout shape)."""
        return self.layout.numel()

    # -- Display -----------------------------------------------------------

    @property
    def names(self) -> frozenset[str]:
        """Human-readable names registered for this axis (may be empty)."""
        return frozenset(_mesh_axis_names.get(self, ()))

    def _layout_str(self) -> str:
        """Format the layout as a compact string (e.g. '4:1')."""
        shape = self.layout.shape
        stride = self.layout.stride
        return f"{shape}:{stride}"

    def __repr__(self) -> str:
        names = _mesh_axis_names.get(self)
        if _debug_repr:
            layout = self._layout_str()
            if names:
                name_str = "/".join(sorted(names))
                return f"{name_str}{{{layout}}}"
            return f"MeshAxis({layout})"
        else:
            if names:
                return sorted(names)[0]
            return f"MeshAxis({self._layout_str()})"

    # -- Construction helpers ----------------------------------------------

    @staticmethod
    @overload
    @staticmethod
    def of(size: int, stride: int) -> MeshAxis: ...

    @overload
    @staticmethod
    def of(pg: ProcessGroup) -> MeshAxis: ...

    @staticmethod
    def of(size_or_pg: int | ProcessGroup, stride: int | None = None) -> MeshAxis:
        """Create a MeshAxis from a size+stride pair or a ProcessGroup.

        When called with an int, *stride* is required::

            MeshAxis.of(4, 1)   # equivalent to MeshAxis(_MeshLayout((4,), (1,)))
            MeshAxis.of(4, 2)   # equivalent to MeshAxis(_MeshLayout((4,), (2,)))

        When called with a ProcessGroup, converts it to a MeshAxis (cached).
        If the ProcessGroup has a ``group_desc`` that is set and not
        ``"undefined"``, the name is registered in the global side table::

            MeshAxis.of(pg)
        """
        if isinstance(size_or_pg, int):
            if stride is None:
                raise TypeError(
                    "MeshAxis.of(size, stride) requires both size and stride"
                )
            return MeshAxis(_MeshLayout((size_or_pg,), (stride,)))
        if stride is not None:
            raise TypeError(
                "stride cannot be specified when constructing from a ProcessGroup"
            )
        return _from_pg(size_or_pg)


def _from_pg(pg: ProcessGroup) -> MeshAxis:
    """Convert a ProcessGroup to a MeshAxis, caching the result."""
    cached = _pg_to_mesh_axis.get(pg)
    if cached is not None:
        return cached

    ranks = _dist.dist.get_process_group_ranks(pg)
    if not ranks:
        raise ValueError("ProcessGroup has no ranks")

    if len(ranks) == 1:
        # Single-rank group: trivial layout.
        layout = _MeshLayout(1, 1)
    else:
        sorted_ranks = sorted(ranks)
        offset = sorted_ranks[0]
        zero_based = [r - offset for r in sorted_ranks]
        shape, strides = _indices_to_layout(zero_based)
        layout = _MeshLayout(shape, strides)

    axis = MeshAxis(layout)

    # Register name from group_desc if available.
    desc = getattr(pg, "group_desc", None)
    if desc and desc != "undefined":
        _register_name(axis, desc)

    _pg_to_mesh_axis[pg] = axis
    return axis


def _register_name(axis: MeshAxis, name: str) -> None:
    """Register a human-readable name for a MeshAxis."""
    names = _mesh_axis_names.get(axis)
    if names is None:
        _mesh_axis_names[axis] = {name}
    else:
        names.add(name)


def set_printoptions(*, debug: bool) -> contextlib.AbstractContextManager[None]:
    """Control MeshAxis repr format.

    Can be used as a statement or as a context manager::

        set_printoptions(debug=True)           # permanent
        with set_printoptions(debug=True):     # scoped, restores on exit
            ...

    Args:
        debug: When True, repr shows all names and layout in curly braces
            (e.g. ``TP/SP{4:1}``).  When False (default), repr shows only
            the first name (e.g. ``TP``), or falls back to
            ``MeshAxis(shape:stride)`` if unnamed.
    """
    global _debug_repr
    old = _debug_repr
    _debug_repr = debug

    @contextlib.contextmanager
    def _restore() -> Generator[None, None, None]:
        try:
            yield
        finally:
            global _debug_repr
            _debug_repr = old

    return _restore()


def _reset() -> None:
    """Reset all MeshAxis state: name registry, PG mappings, and print options.

    Call this when the distributed environment is torn down (e.g., between
    test classes) so that stale name registrations from dead ProcessGroups
    don't pollute subsequent tests.
    """
    global _debug_repr
    _mesh_axis_names.clear()
    _pg_to_mesh_axis.clear()
    _debug_repr = False
